# Generated by Django 4.2.6 on 2024-03-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blood_donation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, null='True')),
                ('mobile_no', models.CharField(max_length=90, null='True')),
                ('email', models.EmailField(max_length=89, null='True')),
                ('blood_group', models.CharField(max_length=90, null='True')),
                ('age', models.CharField(max_length=90, null='True')),
                ('weight', models.CharField(max_length=90, null='True')),
                ('any_health_issue', models.CharField(max_length=90, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='buy1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=90, null='True')),
                ('Manufacturing_date', models.CharField(max_length=90, null='True')),
                ('expiry_date', models.CharField(max_length=80, null='True')),
                ('name', models.CharField(max_length=90, null='True')),
                ('mobile_no', models.CharField(max_length=70, null='True')),
                ('email', models.EmailField(max_length=89, null='True')),
                ('address', models.CharField(max_length=90, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='equipment_buy1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_name', models.CharField(max_length=90, null='True')),
                ('name', models.CharField(max_length=90, null='True')),
                ('mobile_no', models.CharField(max_length=70, null='True')),
                ('email', models.EmailField(max_length=89, null='True')),
                ('address', models.CharField(max_length=90, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='ngologin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=80, null='True')),
                ('pass1', models.CharField(max_length=90, null='True')),
                ('fname', models.CharField(max_length=80, null='True')),
                ('address', models.CharField(max_length=90, null='True')),
                ('email', models.EmailField(max_length=90, null='True')),
                ('mobileno', models.CharField(max_length=90, null='True')),
                ('ngo_start_date', models.CharField(max_length=90, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='upload_equipment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, null='True')),
                ('mobile_no', models.CharField(max_length=90, null='True')),
                ('email', models.EmailField(max_length=89, null='True')),
                ('equipment_name', models.CharField(max_length=90, null='True')),
                ('image', models.ImageField(null='True', upload_to='images')),
                ('quantity', models.CharField(max_length=90, null='True')),
                ('description', models.CharField(max_length=500, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='upload_medicine1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, null='True')),
                ('mobile_no', models.CharField(max_length=10, null='True')),
                ('email', models.EmailField(max_length=90, null='True')),
                ('expiry_date', models.CharField(max_length=10, null='True')),
                ('image', models.ImageField(null='True', upload_to='images')),
                ('medicine_name', models.CharField(max_length=89, null='True')),
                ('quantity', models.CharField(max_length=90, null='True')),
                ('description', models.CharField(max_length=500, null='True')),
                ('Manufacturing_date', models.CharField(max_length=10, null='True')),
            ],
        ),
    ]
